version: '3'
services:

  endpoint:
    image: esmartit/access-point-incoming-endpoint:latest
    ports:
      - "9001:9000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_HOST: "kafka:9092"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-streamlistener
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "smartpoke-device-presence:1:1,smartpoke-device-position:1:1,smartpoke-unique-devices-detected-count:1:1,smartpoke-hourly-presence-count:1:1,smartpoke-sensor-settings:1:1:compact,smartpoke-daily-unique-devices-detected-count:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
