spring.application.name: smartpoke-live-stream-counters
server.port: "${SERVER_PORT:9000}"
spring:
  jmx:
    enabled: false
  cloud.stream:
    kafka:
      streams:
        binder:
          brokers: "${KAFKA_BROKER_HOST}"
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            commit.interval.ms: 1000
    bindings:
      input:
        destination: "smartpoke-device-presence"
        group: "smartpoke.live.stream.counters"
      output:
        destination: "smartpoke-unique-devices-detected-count"
      presence-input:
        destination: "smartpoke-device-presence"
        group: "smartpoke.live.stream.counters.presence"
      presence-output:
        destination: "smartpoke-hourly-presence-count"
      sensor-settings-input:
        destination: "smartpoke-sensor-settings"
        consumer.materializedAs: sensor-settings-store