spring.application.name: smartpoke-live-stream-counters
server.port: "${SERVER_PORT:9000}"
spring:
  jmx:
    enabled: false
  cloud.stream:
    kafka:
      streams:
        binder:
          brokers: "${KAFKA_BROKER_HOST}"
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            commit.interval.ms: 1000
    bindings:
      input:
        destination: "smartpoke-device-presence"
      output:
        destination: "smartpoke-device-position"
      sensor-settings-input:
        destination: "smartpoke-sensor-settings"
        consumer.materializedAs: sensor-settings-store
      hourly-presence-count-input:
        destination: "smartpoke-device-position"
      hourly-presence-count-output:
        destination: "smartpoke-hourly-presence-count"
      unique-devices-detected-count-input:
        destination: "smartpoke-device-position"
      unique-devices-detected-count-output:
        destination: "smartpoke-unique-devices-detected-count"
      daily-unique-devices-detected-count-input:
        destination: "smartpoke-device-position"
      daily-unique-devices-detected-count-output:
          destination: "smartpoke-daily-unique-devices-detected-count"
